name: ghcr push action

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.*

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.ACCESS_TOKEN }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

   
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: aryan2106/helm-push@4.2.0
        with:
         useOCIRegistry: true
         registry-url:  oci://ghcr.io/${{ github.repository }}
         username: aryan2106
         access-token: ${{ secrets.ACCESS_TOKEN }}
         force: true
         chart-folder: charts
