name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.*

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
           charts_repo_url: "https://aryan2106.github.io/Helm-chart"
           charts_dir: "charts"
        env:
          CR_TOKEN: "${{ secrets.ACCESS_TOKEN }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Push Charts to GHCR
        run: |
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts
          done

